//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneradorRecursos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Localizacion
    {
        public string Nombre { get; set; }
        public string Mensaje { get; set; }
        public string Cultura { get; set; }
        public string Comentario { get; set; }
    }
}
