//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localizacion {
    
    
    public class Constantes {
        
        public static bool CONSTANTE_BOOLEANA = true;
        
        public static string PRIMERA_CONSTANTE = "prueba valor";
        
        public static string SEGUNDA_CONSTANTE = "prueba valor 2";
    }
}
