//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localizacion {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Recursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recursos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localizacion.Recursos", typeof(Recursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string ErrorOtro {
            get {
                return ResourceManager.GetString("ErrorOtro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string ErrorOtro2 {
            get {
                return ResourceManager.GetString("ErrorOtro2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string ErrorOtro3 {
            get {
                return ResourceManager.GetString("ErrorOtro3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Otro.
        /// </summary>
        public static string Otro {
            get {
                return ResourceManager.GetString("Otro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hola Mundo.
        /// </summary>
        public static string Salido {
            get {
                return ResourceManager.GetString("Salido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Otro.
        /// </summary>
        public static string Saludo {
            get {
                return ResourceManager.GetString("Saludo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Otro.
        /// </summary>
        public static string Saludo2 {
            get {
                return ResourceManager.GetString("Saludo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Otro.
        /// </summary>
        public static string Saludo3 {
            get {
                return ResourceManager.GetString("Saludo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Saludo Otro.
        /// </summary>
        public static string SaludoOtro {
            get {
                return ResourceManager.GetString("SaludoOtro", resourceCulture);
            }
        }
    }
}
